--- Makefile	2018-02-16 09:03:16.412794595 +0000
+++ Makefile_ssl	2018-02-16 09:03:33.033161919 +0000
@@ -9,10 +9,10 @@
 # http://www.openssl.org/  Make sure the SSL_TREE definition points to the
 # tree with your OpenSSL installation - depending on how you installed it,
 # it may be in /usr/local instead of /usr/local/ssl.
-#SSL_TREE =     /usr/local/ssl
-#SSL_DEFS =	-DUSE_SSL
-#SSL_INC =	-I$(SSL_TREE)/include
-#SSL_LIBS =	-L$(SSL_TREE)/lib -lssl -lcrypto
+SSL_TREE =     /usr/local/ssl
+SSL_DEFS =	-DUSE_SSL
+SSL_INC =	-I$(SSL_TREE)/include
+SSL_LIBS =	-L$(SSL_TREE)/lib -lssl -lcrypto
 
 
 BINDIR =	/usr/local/bin
